### PR TITLE
admc: translate desc to English

### PR DESCRIPTION
**Pull request by JamiKettunen**
No other package in `lure-repo` has a non-English package description; let's keep things consistent, shall we?

### CODE REVIEW

**Comment by xpamych** [comment]
> No other package in `lure-repo` has a non-English package description; let's keep things consistent, shall we?
And you can also respect the language of the authors of the utility) Automated translation in 2022 allows you to get acquainted with the text written in another language without much difficulty.

**Comment by JamiKettunen** [comment]
@xpamych That's not the issue, the description is supposed to be useful for anyone at a glance to tell what the program is for, you can kind of guess what the tool is for in this case because it already contained `Active Directory`, but if you have to use a translator or look at [the upstream project README](https://github.com/altlinux/admc#readme) (which is in English btw) to figure out what it's meant to be the description has utterly failed at its sole purpose.

**Comment by xpamych** [comment]
@JamiKettunen According to your logic, for me as a Russian-speaking person, any description does not meet its purpose, because I have to use a translator in 99% of cases.

**Comment by JamiKettunen** [comment]
I don't believe LURE itself has localization of any kind yet either, but I think cases like the package description should be translated to the user's preferred language locally when displayed by the `lure` tool according to `LC_*` settings of the Linux system, it would be tedious work to store translations of the description for each package, though that could be another choice to go forward too (and might be better for the web UI if that gets localization support).

**Comment by xpamych** [comment]
Also, I don't want to offend anyone, but if we operate with numbers, there are unlikely to be more English speakers than native Chinese or even Indian speakers, but this does not mean that we have to do a description for everyone in these languages. So the option when the description will be selected in accordance with the locale is the most correct, albeit time-consuming.

**Comment by Arsen6331** [comment]
Let's wait on this until localization is properly implemented. I'll close this PR for now.

**Pull request closed without merging**
