### PR TITLE
add: logseq; upg(discord): 0.0.26; upg(telegram-desktop-bin): 4.7.1; upg(syncthing): 1.23.4; add: hlna-git; fix(steamcmd)

### PR DESCRIPTION
**Pull request by xpamych**
A privacy-first, open-source platform for knowledge management and collaboration

### CODE REVIEW

**Comment by xpamych** [comment]
I don't understand why sometimes the check swears at formatting if it is done through shfmt. All 6 packages were formatted at the same time)

**Review by Elagoht — CHANGES_REQUESTED** [review]
My shfmt outputs also shows there are somethings need to edit. Do you use `shfmt` to format your files? And use Tab space instead of 4 spaces.

```
$ diff lure.sh lure.sh_shfmted
19c19
<     cd "${srcdir}"
---
> 	cd "${srcdir}"
23,28c23,28
<     install -Dm755 "${scriptdir}/steamcmd" "${pkgdir}/usr/bin/steamcmd"
<     install -Dm755 "${srcdir}/steamcmd.sh" "${pkgdir}/usr/share/steamcmd/steamcmd.sh"
<     install -Dm755 "${srcdir}/linux32/crashhandler.so" "${pkgdir}/usr/share/steamcmd/linux32/crashhandler.so"
<     install -Dm755 "${srcdir}/linux32/libstdc++.so.6" "${pkgdir}/usr/share/steamcmd/linux32/libstdc++.so.6"
<     install -Dm755 "${srcdir}/linux32/steamcmd" "${pkgdir}/usr/share/steamcmd/linux32/steamcmd"
<     install -Dm755 "${srcdir}/linux32/steamerrorreporter" "${pkgdir}/usr/share/steamcmd/linux32/steamerrorreporter"
---
> 	install -Dm755 "${scriptdir}/steamcmd" "${pkgdir}/usr/bin/steamcmd"
> 	install -Dm755 "${srcdir}/steamcmd.sh" "${pkgdir}/usr/share/steamcmd/steamcmd.sh"
> 	install -Dm755 "${srcdir}/linux32/crashhandler.so" "${pkgdir}/usr/share/steamcmd/linux32/crashhandler.so"
> 	install -Dm755 "${srcdir}/linux32/libstdc++.so.6" "${pkgdir}/usr/share/steamcmd/linux32/libstdc++.so.6"
> 	install -Dm755 "${srcdir}/linux32/steamcmd" "${pkgdir}/usr/share/steamcmd/linux32/steamcmd"
> 	install -Dm755 "${srcdir}/linux32/steamerrorreporter" "${pkgdir}/usr/share/steamcmd/linux32/steamerrorreporter"
```

```$ diff steamcmd.sh steamcmd.sh_shfmted
8,13c8,13
<     mkdir -p ~/.steam/appcache/
<     mkdir -p ~/.steam/config/
<     mkdir -p ~/.steam/logs/
<     mkdir -p ~/.steam/SteamApps/common/
<     ln -s ~/.steam ~/.steam/root
<     ln -s ~/.steam ~/.steam/steam
---
> 	mkdir -p ~/.steam/appcache/
> 	mkdir -p ~/.steam/config/
> 	mkdir -p ~/.steam/logs/
> 	mkdir -p ~/.steam/SteamApps/common/
> 	ln -s ~/.steam ~/.steam/root
> 	ln -s ~/.steam ~/.steam/steam
17,20c17,20
<     mkdir -p ~/.steam/steamcmd/linux32
<     # steamcmd will replace these files with newer ones itself on first run
<     cp /usr/share/steamcmd/steamcmd.sh ~/.steam/steamcmd/steamcmd.sh
<     cp /usr/share/steamcmd/linux32/steamcmd ~/.steam/steamcmd/linux32/steamcmd
---
> 	mkdir -p ~/.steam/steamcmd/linux32
> 	# steamcmd will replace these files with newer ones itself on first run
> 	cp /usr/share/steamcmd/steamcmd.sh ~/.steam/steamcmd/steamcmd.sh
> 	cp /usr/share/steamcmd/linux32/steamcmd ~/.steam/steamcmd/linux32/steamcmd
```

**Comment by xpamych** [comment]
I use https://github.com/patrickvane/shfmt I don't format anything manually.

**Comment by Arsen6331** [comment]
> I use [patrickvane/shfmt](https://github.com/patrickvane/shfmt) I don't format anything manually.

Ah, you're using a different `shfmt`. LURE uses https://github.com/mvdan/sh/tree/master/cmd/shfmt because it's part of the sh library used for interpreting the build scripts.

**Pull request merged**
