### PR TITLE
2 terminal tool 1 game added

### PR DESCRIPTION
**Pull request by Elagoht**

### CODE REVIEW

**Comment by Arsen6331** [comment]
You don't need the 

```bash
version() {
  printf "$version"
}
```

That's only needed if the version has to be updated every time the package is built, such as with git packages.

**Comment by Arsen6331** [comment]
Also, checksums cannot be equal to `"SKIP"`. It must be an array, so set it to `("SKIP")`

**Comment by Elagoht** [comment]
I fixed glue and applied indentation rules. I think they are ready.

**Comment by Arsen6331** [comment]
Thank you, merging now

**Pull request merged**
