### PR TITLE
add noisetorch checksums

### PR DESCRIPTION
**Pull request by xpamych**

### CODE REVIEW

**Comment by Arsen6331** [comment]
It's best not to add checksums for git repos, as they can change

**Comment by Arsen6331** [comment]
Currently, LURE doesn't use checksums for git repos anyway, as there's no good way to verify them.

**Comment by xpamych** [comment]
Strange, I checked and it works))

**Comment by Arsen6331** [comment]
It works because LURE ignores checksums for git repos

**Comment by xpamych** [comment]
> It works because LURE ignores checksums for git repos
oh) i understud

**Pull request closed without merging**
